eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  address: 127.0.0.1
  port: 9001
  tomcat:
    uri-encoding: utf-8

spring:
   datasource:
     url : jdbc:mysql://localhost:3306/nsd?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
     username : root
     password : root
     driver-class-name : com.mysql.cj.jdbc.Driver
     druid:
      driver-class-name : com.mysql.cj.jdbc.Driver
      initial-size : 5
      max-active : 100
      min-idle : 5
      max-wait : 60000
      pool-prepared-statements : true
      max-pool-prepared-statement-per-connection-size : 20
      validation-query : SELECT 1 FROM DUAL
      validation-query-timeout : 60000
      test-on-borrow : false
      test-on-return : false
      test-while-idle : true
      time-between-eviction-runs-millis : 60000
      min-evictable-idle-time-millis : 100000
      web-stat-filter:
         enabled : true
         url-pattern : /*
         exclusions : /*.js, *.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      stat-view-servlet :
         enabled : true
         url-pattern :  /druid/*
         reset-enable : false
         login-username : admin
         login-password : admin
         allow : 127.0.0.1
      filter :
          stat:
            db-type : mysql
            log-slow-sql : true
            slow-sql-millis : 5000
          wall :
            enabled : true
            db-type : mysql
            config :
              delete-allow : false
              drop-table-allow : false
   http:
     encoding:
       charset: utf-8
       force: true
       enabled: true
   redis:
     database: 0
     host: 127.0.0.1
     port: 6379
     password:
     jedis:
       pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
         timeout: 0
   data:
     mongodb:
       host: 127.0.0.1
       port: 27017
       database: chat
   rabbitmq:
     host: 127.0.0.1
     port: 5672
     username: cai
     password: cai1234
     virtual-host: /recruitment
   application:
     name: recruit-service-test

ribbon:
  eureka:
    enabled: true

mybatis:
 typeAliasesPackage: org.spring.springboot.domain
 mapperLocations: classpath:mapper/*.xml
 configuration:
    map-underscore-to-camel-case: true


mapper:
  mappers: com.nsd.recruitment.tkmapper.MyMapper
  identity: MYSQL 
logging:
  level: 
    org: 
     spring: 
       springboot:
           dao: debug
    
pagehelper:
   reasonable: true
   page-size-zero: true
   params:
      pageNum: start 
      pageSize: limit
   support-methods-arguments: true
  
# params: count=countSql

#自定义参数，可以迁移走
token:
  #redis默认过期时间（2小时）(这是自定义的)(毫秒)
  expirationMilliSeconds: 7200000



